module RentManager
  class Tenant < RentManagerRelation
    def self.base_path
      'Tenants'
    end

    def self.join_tables
      [
        :account_statements,
        :addresses,
        :appointments,
        :billable_expenses,
        :cash_pay_user,
        :charges,
        :color,
        :contacts,
        :create_user,
        :credit_reversals,
        :credits,
        :history,
        :history_calls,
        :history_emails,
        :history_notes,
        :history_system_notes,
        :history_violation_notes,
        :history_visits,
        :invoices,
        :late_fee_setup,
        :leases,
        :leasing_agent,
        :loans,
        :open_prepays,
        :open_receivables,
        :override_create_user,
        :override_update_user,
        :payment_reversals,
        :payments,
        :pets,
        :property,
        :prospect,
        :rm_vo_ip_call_history,
        :recurring_charge_summaries,
        :recurring_charges,
        :revenue_renewals,
        :screenings,
        :security_deposit_summaries,
        :service_manager_projects,
        :short_term_reservations,
        :subsidies,
        :subsidy_tenants,
        :tasks,
        :tenant_bills,
        :tenant_checks,
        :transactions,
        :update_user,
        :user_defined_values,
        :vehicles,
        :violations,
        :web_user_accounts,
        :web_users
      ]
    end
  end
end
